name: Go

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Make manifests
        run: make manifests

      - name: Upload crds
        uses: actions/upload-artifact@v2
        with:
          name: crds
          path: config/crd/bases

  pull_def_repo:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Pull operator definitions repository
        uses: actions/checkout@v2
        with:
          repository: pickjonathan/alertojon.io-operator-definition
          ref: develop
          token: ${{ secrets.my_pat }}

      - name: download crds
        uses: actions/download-artifact@v2
        with:
          name: crds
          path: config/crd/bases

      - name: copy crds
        run: cp -r config/crd/bases/* .

      - name: commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@alertojon.io
          branch: develop
          branch_mode: create
          committer_name:  ${{ github.actor }}
          committer_email: ${{ github.actor }}@alertojon.io
          default_author: github_actions
          message: "Updated CRDs"
          pathspec_error_handling: ignore
          pull: 'NO-PULL or --rebase --autostash ...'
#          tag: 'v1.0.0 --force'
