name: Push-crds

on:
  pull_request:
    branches:
      - develop
    paths:
      - config/crd/bases/*.yaml

jobs:

  pull_def_repo:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Pull operator definitions repository
        uses: actions/checkout@v2
        with:
          repository: pickjonathan/alertojon.io-operator-definition
          ref: develop
          token: ${{ secrets.my_pat }}

      - name: download crds
        uses: actions/download-artifact@v2
        with:
          name: crds
          path: bases

      - name: copy crds
        run: cp -r bases/* config/crd/bases/ && rm -rf bases

      - name: commit and push
        run: git config --global user.email "pickjonathan@alertojon.io" && git config --global user.name pickjonathan && git add . && git commit -m "update crds" && git push origin develop